site_name: üß™ Laborat√≥rio de Estudos .NET
site_url: https://heviane.github.io/dotnet-lab/
repo_url: https://github.com/heviane/dotnet-lab
repo_name: heviane/dotnet-lab
edit_uri: edit/main/docs/ # Ajuste para apontar para a pasta de documenta√ß√£o

theme:
  name: material
  language: pt
  palette:
    # Palette toggle for light vs dark mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro
    # Palette toggle for dark vs light mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

# √â uma boa pr√°tica definir explicitamente o diret√≥rio dos documentos.
docs_dir: docs

nav:
  - "In√≠cio": index.md
  - "Guias de Projetos":
      - "Requisitos": requirements-guide.md
      - ".NET CLI": dotnet-cli-guide.md
      - "Versionamento": versioning-guide.md
  - "Cursos e Anota√ß√µes":
      - "Conceitos Gerais": courses/conceitos-gerais-programacao.md
